
#define TRACK_HEIGHT 50.0f
#define PADDING_LEFT 15.0f
#define PADDING 15.0f
#define TRACK_TOP_PADDING 30.0
#define TRACK_BOTTOM_MARGIN 12.0f

#define PIXELS_PER_FRAME_AT_MAX_ZOOM 10.0f
#define PIXELS_PER_FRAME_AT_MID_ZOOM 4.0f
#define PIXELS_PER_FRAME_AT_MIN_ZOOM 0.1f
